[general]
live_config_reload = true

[window]
dynamic_padding = true
decorations = "Transparent"
decorations_theme_variant = "Dark"
opacity=0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
